### ISSUE TITLE
运行成功，没有自动回复功能啊

### ISSUE THREAD

**Issue by lebornjose** [fritx/wxbot#13]
npm run start 可以正常启动，  运行  electron .  则会报错，错误代码

`fs.js:634
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '/usr/local/lib/node_modules/electron-prebuilt/path.txt'
    at Error (native)
    at Object.fs.openSync (fs.js:634:18)
    at Object.fs.readFileSync (fs.js:502:33)
    at Object.<anonymous> (/usr/local/lib/node_modules/electron-prebuilt/index.js:4:42)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)`

**Comment by fritx** [comment]
看起来是global的electron没安装好 可以试下重新装
直接 electron . 是调了global的
npm start 是调项目内的
