### ISSUE TITLE
启动错误

### ISSUE THREAD

**Issue by freedomlang** [fritx/wxbot#6]
错误信息如下

```
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Cannot find module 'browser-window'
    at Module._resolveFilename (module.js:438:15)
    at Function.Module._resolveFilename (/usr/local/lib/node_modules/electron-prebuilt/dist/resources/electron.asar/common/reset-search-paths.js:47:12)
    at Function.Module._load (module.js:386:25)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/root/wxbot/index.js:1:100)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
```

是我的electron的安装问题？BTW：electron的版本是1.2

**Comment by fritx** [comment]
@freedomlang 噢 不好意思 可能是electronv1.x 开始废弃旧的用法了 你可以改用0.x版本
http://electron.atom.io/docs/
或者尝试一下对index.js&preload.js 做如下修改

``` js
require('app')
require('browser-window')
require('clipboard')
require('native-image')
// =>
require('electron').app
require('electron').BrowserWindow
require('electron').clipboard
require('electron').nativeImage
```

**Comment by freedomlang** [comment]
@fritx 按照官方的api说明修改后，可以启动了。但是，画面卡在登录成功的界面，并没有成功跳转微信客户端的界面。会不会连preload都变了？
[https://github.com/electron/electron/blob/master/docs/api/process.md#event-loaded](url)

**Comment by fritx** [comment]
是这个 http://electron.atom.io/docs/api/browser-window/
webPreferences: { nodeIntegration, preload }  似乎还没变
不过可能正式废弃了旧写法 改驼峰试试？

**Comment by freedomlang** [comment]
这个我已经改了。如果不改就连网页都出不来，只有背景！但登录成功后就是不跳转，是不是IPC的问题？
```
var win = new BrowserWindow({
		width: 900,
		height: 610,
		webPreferences: {
			nodeIntegration: false,
			webSecurity: true,
			preload: __dirname + '/preload.js'
		}
	})
```

**Comment by fritx** [comment]
:+1: 参照commit: https://github.com/huangruichang/md-editor/commit/08ad6995466f10e4252876f8c5b3770737e83980
cc @huangruichang

**Comment by freedomlang** [comment]
@fritx 还是不行，就是跳转不了！问题还是在preload.js那里。以下是修改的地方！
index.js

```
var app = require('electron').app
var BrowserWindow = require('electron').BrowserWindow
var ipc = require('electron').ipcRenderer

webPreferences: {
            nodeIntegration: false,
            preload: __dirname + '/preload.js'
        }

win.loadURL('https://wx.qq.com/?lang=zh_CN&t=' + Date.now())
```

preload.js

```
var clipboard = require('electron').clipboard
var NativeImage = require('electron').nativeImage
var ipc = require('electron').ipcRenderer
```

PS:终端没有任何提示！

**Comment by huangruichang** [comment]
amazing :+1:

**Comment by freedomlang** [comment]
诡异的是：我翻了一下官方的[文档](http://electron.atom.io/docs/api/process/#event-loaded)，发现有`process.type`这一属性。我把这个属性设置成`browser`就可以跳转了，但是终端还是没有提示！

我在init函数的开头添加alert测试了一下，是有反映的！是不是下面挂掉了？

```
window._console = window.console

function debug(/*args*/){
    var args = JSON.stringify(_.toArray(arguments))
    _console.log(args)
}
```

**Comment by robert-heng** [comment]
![image](https://cloud.githubusercontent.com/assets/16911488/16030854/fd389836-3227-11e6-8ea0-189d54048e27.png)

**Comment by robert-heng** [comment]
![image](https://cloud.githubusercontent.com/assets/16911488/16030860/125501c8-3228-11e6-91ea-bfd213a18908.png)

**Comment by fritx** [comment]
@freedomlang OK了

**Comment by freedomlang** [comment]
@fritx 还是不跳转>_<，微信上点击登录了，但网页上还停留在提示“在手机上确认登录的画面”！

**Comment by fritx** [comment]
怪了。。我上周末是ok的。。electron v1.2.5

**Comment by freedomlang** [comment]
@fritx 测试系统是Linux && electron 1.2.0。我在`preload.js` 的开头加上`process.type="browser"` 就可以进去了，但是自动回复功能有问题，终端提示回复了，但界面直接卡死了。从手机看也没有发现有自动回复过！
